### ISSUE TITLE
broken appearance on WordPress 5.5 

### ISSUE THREAD

**Issue by ptesei** [7studio/acf-color-palette#5]
WordPress updated his color picker so a couple of css adjustments are needed.
Hello i've created a couple of pull request to fix the problem,let me know if it works for you !
#4 #3

**Comment by 7studio** [comment]
Hi @ptesei,

Thank you for your contribution. 

The problem comes from [kallookoo/wp-color-picker-alpha](kallookoo/wp-color-picker-alpha) and will be fixed by #7 

I close your pull requests and will fix all problems with WP 5.5 quickly.
